<?php

namespace App\Modules\Auth\Requests;

use App\Modules\Auth\Abstracts\BaseUserRequest;
use App\Modules\Auth\Enums\UserStatus;
use Carbon\Carbon;

class UserRetireRequest extends BaseUserRequest
{
    public function rules(): array
    {
        return [
            /**
             * Status (generated by server)
             * @ignoreParam
             */
            "status" => parent::rules()["status"],
            /**
             * Retire timestamp (generated by server)
             * @ignoreParam
             */
            "retired_at" => ["required", "date", "after_or_equal:now"],
        ];
    }

    public function prepareForValidation(): void
    {
        parent::prepareForValidation();

        $this->merge([
            "retired_at" => Carbon::now(),
            "status" => UserStatus::RETIRED->value,
        ]);
    }
}
