<?php

namespace App\Modules\Auth\Requests;

use App\Modules\Auth\Abstracts\BaseUserRequest;
use App\Modules\Auth\Enums\UserStatus;
use Carbon\Carbon;

class UserSuspendRequest extends BaseUserRequest
{
    public function authorize(): bool
    {
        return false;
    }
    public function rules(): array
    {
        return [
            /**
             * Status (generated by server)
             * @ignoreParam
             */
            "status" => parent::rules()["status"],
            /**
             * Suspension end timestamp (generated by server)
             *
             * @example 2030-12-01 00:00:00
             */
            "suspension_ended_at" => ["required", "date", "after:today"],
            /**
             * Suspension start timestamp (generated by server)
             * @ignoreParam
             */
            "suspension_started_at" => ["required", "date"],
            /**
             * Suspension note (reason)
             * @example Spam
             */
            "suspension_note" => ["required", "string", "max:500"],
        ];
    }

    public function prepareForValidation(): void
    {
        parent::prepareForValidation();
        $this->merge([
            "suspension_started_at" => Carbon::now(),
            "status" => UserStatus::SUSPENDED->value,
        ]);
    }
}
