<?php

namespace App\Modules\Auth\Requests;

use App\Modules\Auth\Abstracts\BaseUserRequest;
use App\Modules\Auth\Enums\UserStatus;

class UserActivateRequest extends BaseUserRequest
{
    public function rules(): array
    {
        return [
            /**
             * Status (generated by server)
             * @ignoreParam
             */
            "status" => parent::rules()["status"],
        ];
    }

    public function prepareForValidation(): void
    {
        $this->merge([
            "status" => UserStatus::ACTIVE->value,
        ]);

        parent::prepareForValidation();
    }
}
