<?php

namespace App\Modules\Auth\Requests;

use App\Modules\Auth\Abstracts\BaseUserRequest;
use App\Modules\Auth\Enums\UserStatus;
use App\Modules\Auth\Models\User;
use App\Modules\Auth\Rules\UserStatusTransitionsFromRule;
use Carbon\Carbon;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\Rule;

class UserRetireRequest extends BaseUserRequest
{
    public function rules(): array
    {
        return [
            /**
             * Status === RETIRED
             * @ignoreParam
             */
            "status" => [
                "required",
                Rule::enum(UserStatus::class)->only(UserStatus::RETIRED),
                new UserStatusTransitionsFromRule($this->getQueriedUserOrFail()->status),
            ],
            /**
             * Retire timestamp (generated by server)
             * @ignoreParam
             */
            "retired_at" => ["required", "date", "after_or_equal:now"],
        ];
    }

    public function authorize(): bool
    {
        Gate::authorize("retire", User::class);
        return true;
    }

    public function prepareForValidation(): void
    {
        parent::prepareForValidation();

        $this->merge([
            "retired_at" => Carbon::now(),
            "status" => UserStatus::RETIRED->value,
        ]);
    }
}
