<?php

namespace App\Modules\Recruitment\Requests;

use App\Modules\Proposal\Rules\RecruitmentStatusTransitionsFromRule;
use App\Modules\Recruitment\Abstracts\BaseRecruitmentRequest;
use App\Modules\Recruitment\Enums\RecruitmentStatus;
use App\Modules\Recruitment\Models\Recruitment;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\Rule;

class RecruitmentCloseRequest extends BaseRecruitmentRequest
{
    public Recruitment $recruitment;

    public function rules(): array
    {
        return [
            /**
             * Initial status (generated by server)
             * @ignoreParam
             */
            "status" => [
                "required",
                Rule::enum(RecruitmentStatus::class)->only(RecruitmentStatus::CLOSED),
                new RecruitmentStatusTransitionsFromRule($this->recruitment->status),
            ],
            /**
             * Close timestamp (generated by server)
             * @ignoreParam
             */
            "closed_at" => ["required", "date"],
        ];
    }

    public function authorize(): bool
    {
        Gate::authorize("close", Recruitment::class);
        return true;
    }

    public function prepareForValidation(): void
    {
        parent::prepareForValidation();

        $this->recruitment = Recruitment::findOrFail($this->route("id"));

        $this->merge([
            "status" => RecruitmentStatus::CLOSED->value,
            "closed_at" => Carbon::now(),
        ]);
    }
}
