<?php

namespace App\Modules\Recruitment\Requests;

use App\Modules\Proposal\Enums\ProposalStatus;
use App\Modules\Proposal\Rules\ProposalExistsWithStatusRule;
use App\Modules\Recruitment\Abstracts\BaseRecruitmentRequest;
use App\Modules\Recruitment\Enums\RecruitmentStatus;
use App\Modules\Recruitment\Models\Recruitment;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\Rule;

class RecruitmentStoreRequest extends BaseRecruitmentRequest
{
    public function rules(): array
    {
        return [
            ...parent::rules(),
            ...[
                /**
                 * Initial status (generated by server)
                 * @ignoreParam
                 */
                "status" => ["required", Rule::enum(RecruitmentStatus::class)->only(RecruitmentStatus::DRAFT)],
                /**
                 * Created by user (generated by server)
                 * @ignoreParam
                 */
                "created_by_user_id" => ["required", "integer:strict"],
                /**
                 * Id of proposal for this recruitment
                 * @example 1
                 */
                "proposal_id" => ["required", "integer", new ProposalExistsWithStatusRule(ProposalStatus::APPROVED)],
            ],
        ];
    }

    public function authorize(): bool
    {
        Gate::authorize("create", Recruitment::class);
        return true;
    }

    public function prepareForValidation(): void
    {
        parent::prepareForValidation();

        $this->merge([
            "created_by_user_id" => Auth::user()->id,
            "status" => RecruitmentStatus::DRAFT->value,
        ]);
    }
}
