<?php

namespace App\Modules\Recruitment\Requests;

use App\Modules\Recruitment\Abstracts\BaseRecruitmentRequest;
use App\Modules\Recruitment\Enums\RecruitmentStatus;
use App\Modules\Recruitment\Models\Recruitment;
use App\Modules\Recruitment\Rules\RecruitmentStatusTransitionsFromRule;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\Rule;

class RecruitmentCloseRequest extends BaseRecruitmentRequest
{
    public function rules(): array
    {
        return [
            /**
             * Initial status (generated by server)
             * @ignoreParam
             */
            "status" => [
                "bail",
                "required",
                Rule::enum(RecruitmentStatus::class)->only(RecruitmentStatus::CLOSED),
                new RecruitmentStatusTransitionsFromRule($this->getQueriedRecruitmentOrFail()->status),
            ],
            /**
             * Close timestamp (generated by server)
             * @ignoreParam
             */
            "actual_closed_at" => ["required", "date"],
            /**
             * Id of user who closed (generated by server)
             * @ignoreParam
             */
            "closed_by_user_id" => ["required", "integer:strict"],
        ];
    }

    public function authorize(): bool
    {
        Gate::authorize("close", Recruitment::class);
        return true;
    }

    public function prepareForValidation(): void
    {
        parent::prepareForValidation();

        $this->merge([
            "status" => RecruitmentStatus::CLOSED->value,
            "actual_closed_at" => Carbon::now(),
            "closed_by_user_id" => Auth::user()->id,
        ]);
    }
}
