<?php

namespace App\Modules\Recruitment\Requests;

use App\Modules\Recruitment\Abstracts\BaseRecruitmentRequest;
use App\Modules\Recruitment\Enums\RecruitmentStatus;
use App\Modules\Recruitment\Rules\RecruitmentStatusTransitionsFromRule;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\Rule;

class RecruitmentScheduleRequest extends BaseRecruitmentRequest
{
    public function rules(): array
    {
        return [
            /**
             * Initial status (generated by server)
             * @ignoreParam
             */
            "status" => [
                "bail",
                "required",
                Rule::enum(RecruitmentStatus::class)->only(RecruitmentStatus::SCHEDULED),
                new RecruitmentStatusTransitionsFromRule($this->getQueriedRecruitmentOrFail()->status),
            ],
            /**
             * Scheduled start time
             * @example 2025-08-10
             */
            "scheduled_publish_at" => ["required", "date", "after:now"],
            /**
             * Scheduled end time
             * @example 2025-11-10
             */
            "scheduled_close_at" => ["required", "date", "after:scheduled_publish_at"],
        ];
    }

    public function authorize(): bool
    {
        Gate::authorize("schedule", $this->getQueriedRecruitmentOrFail());
        return true;
    }

    public function prepareForValidation(): void
    {
        parent::prepareForValidation();

        $this->merge([
            "status" => RecruitmentStatus::SCHEDULED->value,
            "closed_at" => Carbon::now(),
        ]);
    }
}
