<?php

namespace App\Modules\Recruitment\Requests;

use App\Modules\Recruitment\Abstracts\BaseRecruitmentRequest;
use App\Modules\Recruitment\Enums\RecruitmentStatus;
use App\Modules\Recruitment\Models\Recruitment;
use App\Modules\Recruitment\Rules\RecruitmentStatusTransitionsFromRule;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\Rule;

class RecruitmentPublishRequest extends BaseRecruitmentRequest
{
    public function rules(): array
    {
        return [
            /**
             * Initial status (generated by server)
             * @ignoreParam
             */
            "status" => [
                "bail",
                "required",
                Rule::enum(RecruitmentStatus::class)->only(RecruitmentStatus::PUBLISHED),
                new RecruitmentStatusTransitionsFromRule($this->getQueriedRecruitmentOrFail()->status),
            ],
            /**
             * Publish timestamp (generated by server)
             * @ignoreParam
             */
            "actual_published_at" => ["required", "date"],
        ];
    }

    public function authorize(): bool
    {
        Gate::authorize("publish", Recruitment::class);
        return true;
    }

    public function prepareForValidation(): void
    {
        parent::prepareForValidation();

        $this->merge([
            "status" => RecruitmentStatus::PUBLISHED->value,
            "actual_published_at" => Carbon::now(),
        ]);
    }
}
